---
version: '2'

services:
  db:
    image: mysql:5.5
    container_name: directory_db
    restart: always
    volumes:
      - ./symfony.sql:/docker-entrypoint-initdb.d/symfony.sql
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web:
    image: reg.hcpss.org/directory/directory_web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: directory_web
    restart: always
    links:
      - db:symfony_db
    volumes:
      - ./symfony:/var/www/symfony
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SYMFONY_SECRET: ${SYMFONY_SECRET}
    ports:
      - 9090:80
