---
version: '2'
services:

  graph:
    image: neo4j
    container_name: directory_graph
    restart: always
    volumes:
      - ./.node_data:/data
      - ./.node_logs:/logs
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH_USERNAME}/${NEO4J_AUTH_PASSWORD}

  search:
    container_name: directory_search
    image: elasticsearch:5
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  web:
    image: reg.hcpss.org/directory/web:glamorous_cheetah
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: directory_web
    restart: always
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - 9090:80
    environment:
      APP_ENV: dev
      NEO4J_AUTH_USERNAME: ${NEO4J_AUTH_USERNAME}
      NEO4J_AUTH_PASSWORD: ${NEO4J_AUTH_PASSWORD}
