---
version: '2'

services:
  db:
    image: mysql:5.7
    container_name: directory_db
    restart: always
    volumes:
      - ./symfony.sql:/docker-entrypoint-initdb.d/symfony.sql
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  search:
    container_name: directory_search
    image: elasticsearch:5
    environment:
      - discovery.type=single-node
    #image: solr:8
    #command: "solr-create -c mycore"
    
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
##      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    mem_limit: 1g
    #volumes:
    #  - esdata1:/usr/share/elasticsearch/data
  web:
    image: reg.hcpss.org/directory/directory_web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: directory_web
    restart: always
    volumes:
      - ./symfony:/var/www/symfony
    environment:
      #DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      APP_SECRET: ${SYMFONY_SECRET}
      APP_ENV: dev

      #TRUSTED_HOSTS: "'^localhost|^directory\.hcpss\.org$'"
      #MAILER_URL: null://localhost
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    ports:
      - 9090:80
