<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends EntityRepository
{
	public function findAllOrderedByName($searchTerm) {
		$staff = $this->getEntityManager()
    ->createQuery(
        "SELECT staff
        FROM AppBundle:Staff staff
        WHERE CONCAT(staff.firstName, ' ', staff.lastName) LIKE '%$searchTerm%'
        ORDER BY staff.lastName ASC"
    )
    ->getResult();
        //$a = array();
        //foreach ($staff as $staff_member) {
            //$a[$staff_member->getEmail()] = $staff_member;
        //}
        return $staff;
	}   

	public function findDeptOrderedByNameOnce() {
		return $this->getEntityManager()
    ->createQuery(
        "SELECT a.name, a.slug
        FROM AppBundle:Department a
        GROUP BY a.name"
    )
    ->getResult();
	}

    public function findStaffPhone($searchPhone) {
        return $this->getEntityManager()
    ->createQuery(
        "SELECT staff
        FROM AppBundle:Staff staff
        WHERE staff.phone LIKE '%$searchPhone%'
        ORDER BY staff.lastName ASC"
    )
    ->getResult();
    }     
}
