neo4j:
    connections:
        default:
            scheme: bolt
            host: graph
            port: 7687
            username: '%env(NEO4J_AUTH_USERNAME)%'
            password: '%env(NEO4J_AUTH_PASSWORD)%'
    clients:
        default:
            connections: [default]
